package PGR208.exam.edamamapp.models

data class TotalDaily2 (
    val sugarAdded : Nutrient = Nutrient("SUGAR.added", "Added sugar", 0.0, "g"),
    val calcium : Nutrient = Nutrient("CA", "Calcium", 0.0, "mg"),
    val carbohydrateNet: Nutrient = Nutrient("CHOCDF.net","Carbohydrate (net)",0.0, "g"),
    val carbohydrateByDifference: Nutrient = Nutrient("CHOCDF", "Carbohydrate, by difference", 0.0,	"g"),
    val cholesterol: Nutrient = Nutrient("CHOLE","Cholesterol", 0.0,"mg"),
    val energy: Nutrient = Nutrient("ENERC_KCAL", "Energy", 0.0, "kcal"),
    val fattyAcidsMonosaturated: Nutrient = Nutrient("FAMS", "Fatty acids, total monounsaturated", 0.0, "g"),
    val fattyAcidsPolysaturated: Nutrient = Nutrient("FAPU", "Fatty acids, total polyunsaturated", 0.0, "g"),
    val fattyAcidsSaturated: Nutrient = Nutrient("FASAT", "Fatty acids, total saturated", 0.0, "g"),
    val fattyAcidsTrans: Nutrient = Nutrient("FATRN", "Fatty acids, total trans", 0.0, "g"),
    val fiber: Nutrient = Nutrient("FIBTG", "Fiber, total dietary", 0.0, "g"),
    val folateDFE: Nutrient = Nutrient("FOLDFE", "Folate, DFE", 0.0, "µg"),
    val folateFood: Nutrient = Nutrient("FOLFD", "Folate, food", 0.0, "µg"),
    val folicAcid: Nutrient = Nutrient("FOLAC", "Folic Acid", 0.0, "µg"),
    val iron: Nutrient = Nutrient("FE", "Iron, Fe", 0.0, "mg"),
    val magnesium: Nutrient = Nutrient("MG", "Magnesium", 0.0, "mg"),
    val nacin: Nutrient = Nutrient("NIA", "Niacin", 0.0, "mg"),
    val phosphorus: Nutrient = Nutrient("P", "Phosphorus, P", 0.0, "mg"),
    val potassium: Nutrient = Nutrient("K", "Potassium, K", 0.0, "mg"),
    val protein: Nutrient = Nutrient("PROCNT", "Protein", 0.0, "g"),
    val riboflavin: Nutrient = Nutrient("RIBF", "Riboflavin", 0.0, "mg"),
    val sodium: Nutrient = Nutrient("NA", "Sodium, NA", 0.0, "mg"),
    val sugarAlcohol: Nutrient = Nutrient("Sugar.Alcohol", "Sugar alcohols", 0.0, "g"),
    val sugar: Nutrient = Nutrient("SUGAR", "Sugars, total", 0.0, "g"),
    val thiamin: Nutrient = Nutrient("THIA", "Thiamin", 0.0, "mg"),
    val totalLipid: Nutrient = Nutrient("FAT", "Total lipid (fat)", 0.0, "g"),
    val vitA: Nutrient = Nutrient("VITA_RAE", "Vitamin A, RAE", 0.0, "µg"),
    val vitB12: Nutrient = Nutrient("VITB12", "Vitamin B-12", 0.0, "µg"),
    val vitB6A: Nutrient = Nutrient("VITB6A", "Vitamin B-6", 0.0, "mg"),
    val vitC: Nutrient = Nutrient("VITC", "Vitamin C, total ascorbic acid", 0.0, "mg"),
    val vitD: Nutrient = Nutrient("VITD", "Vitamin D (D2 + D3)", 0.0, "µg"),
    val vitE: Nutrient = Nutrient("TOCPHA", "Vitamin E (alpha-tocopherol)", 0.0, "mg"),
    val vitK: Nutrient = Nutrient("VITK1", "Vitamin K (phylloquinone)", 0.0, "µg"),
    val water: Nutrient = Nutrient("WATER", "Water", 0.0, "g"),
    val zinc: Nutrient = Nutrient("ZN", "Zinc, Zn", 0.0, "mg")
)